version: '3.8'
services:
  wordpress:
    image: wordpress:5.6.2-php7.4
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
    restart: always
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: